# Generated by Django 4.1.2 on 2022-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='contact',
            new_name='phone',
        ),
    ]
