# Generated by Django 4.1.2 on 2022-10-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decofor', models.CharField(max_length=50)),
                ('flat', models.CharField(max_length=6)),
                ('cleaning', models.CharField(max_length=3)),
                ('materials', models.CharField(max_length=3)),
            ],
        ),
    ]
