# Generated by Django 4.1.2 on 2022-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_decoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='cleaning',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='flat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='materials',
            field=models.CharField(max_length=50),
        ),
    ]
