# Generated by Django 4.1.2 on 2022-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_decoration_cleaning_alter_decoration_flat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('pass12', models.CharField(max_length=200)),
            ],
        ),
    ]
