# Generated by Django 4.1.2 on 2022-10-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_helper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helper',
        ),
    ]
