# Generated by Django 4.1.2 on 2022-10-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bookdecoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdecoration',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
