# Generated by Django 4.1.2 on 2022-10-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_bookdecoration_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdecoration',
            old_name='Customer_Name',
            new_name='Cust_Name',
        ),
    ]
