# Generated by Django 4.1.2 on 2022-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_customer_name_bookdecoration_cust_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='decofor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
