# Generated by Django 4.1.2 on 2022-10-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_decoration_decofor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdecoration',
            name='Address',
        ),
        migrations.AddField(
            model_name='bookdecoration',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
